crop_x:
  - 880
  - 1280
crop_y:
  - 125
  - 525
bin_x:
  - 910
  - 1255
bin_y:
  - 155
  - 495

# gripper related
length_g: 30
fixed_open_length: 100

# mrcnn initialize
mrcnn_weights_path: 'mask_rcnn_cylinder_0100.h5'

# pose initialize
ae_weights_path: './chkpt-80000'
view_dataset_path: '../pose_dataset/Views'
cfg_file_path: 'grasp_autoencoder_0802.cfg'
experiment_name: 'grasp_autoencoder_0802'


# depth related
ground_depth: 720
guided_para: 30
level_interval: 45

# pose related
border_interval: 30
num_iter: 300

# open grasp
hole_visibility_threshold: 0.8
hole_center_dist_threshold: 2
hole_space_threshold: 0
min_rec_threshold: 30

# close grasp candidates
grasp_pos_interval: 3

grasp_poly_offset_1: 1
grasp_poly_offset_num_1: 3
grasp_poly_offset_2: 1
grasp_poly_offset_num_2: 8
grasp_poly_offset_3: 1
grasp_poly_offset_num_3: 3

# collision
collide_threshold: 35
threshold_offset: 5

# non-maximum suppression
suppression_dist_threshold: 300.0

crop_pose_x:
  - 970
  - 1160
crop_pose_y:
  - 465
  - 650

padding_size: 2000
border_interval_pose: 100

  